export const actionTypes = {
  FETCH_ITEMS: "FETCH_ITEMS",
  ADD_FILTER: "ADD_FILTER",
  DELETE_FILTER: "DELETE_FILTER",
  ADD_TO_WISH_LIST: "ADD_TO_WISH_LIST",
  DELETE_FROM_WISH_LIST: "DELETE_FROM_WISH_LIST",

  ADD_TO_CARD: "ADD_TO_CARD",
  FILTER_BY_AGE: "FILTER_BY_AGE",
  FILTER_BY_THEME: "FILTER_BY_THEME",
  FILTER_BY_PRICE: "FILTER_BY_PRICE",
  ADD_TO_WISH_LIST_CARD: "ADD_TO__CARD",
  DELETE_FROM__CARD: "DELETE_FROM__CARD",
};
